FROM nginx:1.25
RUN rm /etc/nginx/conf.d/default.conf

COPY ./infra/nginx/templates      /etc/nginx/templates/
COPY ./infra/nginx/includes       /etc/nginx/includes/
COPY ./infra/nginx/configurations /etc/nginx/conf.d/
