"""?

Revision ID: 237b4f0f4e6d
Revises: c0db4b0a8fbf
Create Date: 2024-05-21 22:25:41.720346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237b4f0f4e6d'
down_revision: Union[str, None] = 'c0db4b0a8fbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
