"""Fix travel model to use Association Object relation

Revision ID: 3a11e2d7cf7a
Revises: 92cb9b11aad1
Create Date: 2024-05-20 15:07:22.260569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a11e2d7cf7a'
down_revision: Union[str, None] = '92cb9b11aad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel', sa.Column('finished_at', sa.DateTime(), nullable=True))
    op.drop_constraint('travel_id_passenger4_fkey', 'travel', type_='foreignkey')
    op.drop_constraint('travel_id_driver_fkey', 'travel', type_='foreignkey')
    op.drop_constraint('travel_id_passenger3_fkey', 'travel', type_='foreignkey')
    op.drop_constraint('travel_id_passenger2_fkey', 'travel', type_='foreignkey')
    op.drop_constraint('travel_id_passenger1_fkey', 'travel', type_='foreignkey')
    op.drop_column('travel', 'id_passenger4')
    op.drop_column('travel', 'id_passenger3')
    op.drop_column('travel', 'id_passenger1')
    op.drop_column('travel', 'closed_at')
    op.drop_column('travel', 'id_driver')
    op.drop_column('travel', 'id_passenger2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel', sa.Column('id_passenger2', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('travel', sa.Column('id_driver', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('travel', sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('travel', sa.Column('id_passenger1', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('travel', sa.Column('id_passenger3', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('travel', sa.Column('id_passenger4', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('travel_id_passenger1_fkey', 'travel', 'user', ['id_passenger1'], ['id'])
    op.create_foreign_key('travel_id_passenger2_fkey', 'travel', 'user', ['id_passenger2'], ['id'])
    op.create_foreign_key('travel_id_passenger3_fkey', 'travel', 'user', ['id_passenger3'], ['id'])
    op.create_foreign_key('travel_id_driver_fkey', 'travel', 'user', ['id_driver'], ['id'])
    op.create_foreign_key('travel_id_passenger4_fkey', 'travel', 'user', ['id_passenger4'], ['id'])
    op.drop_column('travel', 'finished_at')
    # ### end Alembic commands ###
