"""Add gps to zone and stop

Revision ID: 8d6254c2d575
Revises: 237b4f0f4e6d
Create Date: 2024-05-21 22:57:54.316731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d6254c2d575'
down_revision: Union[str, None] = '237b4f0f4e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stop', sa.Column('gps', sa.String(), nullable=True))
    op.add_column('zone', sa.Column('gps', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone', 'gps')
    op.drop_column('stop', 'gps')
    # ### end Alembic commands ###
