"""Delete gps to zone

Revision ID: 9cb8004b35cd
Revises: b5d24d524e32
Create Date: 2024-05-21 14:45:54.760121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb8004b35cd'
down_revision: Union[str, None] = 'b5d24d524e32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone', 'gps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone', sa.Column('gps', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
