"""Add field in_wait to stops

Revision ID: a3cb0fe8da59
Revises: 97c829fb4bb3
Create Date: 2024-05-28 21:06:07.615667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3cb0fe8da59'
down_revision: Union[str, None] = '97c829fb4bb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stop', sa.Column('in_wait', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stop', 'in_wait')
    # ### end Alembic commands ###
