"""Default is_driver to false

Revision ID: c0db4b0a8fbf
Revises: 9cb8004b35cd
Create Date: 2024-05-21 17:28:55.942858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0db4b0a8fbf'
down_revision: Union[str, None] = '9cb8004b35cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
