"""Initial migration

Revision ID: e98a39d35bf7
Revises: 2ab93a6ffb0a
Create Date: 2024-05-07 14:37:13.788917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98a39d35bf7'
down_revision: Union[str, None] = '2ab93a6ffb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
